### ISSUE TITLE
Can I execute Minecraft server commands within Slack?

### ISSUE THREAD

**Issue by herobrinein** [howyi/SlackChannelSRV#7]

**Comment by herobrinein** [comment]
Can you customize the instruction prefix that triggers instructions in the slot, such as'/'
Can I return the execution instruction after the slot is sent?
Can I set which channels separately to use Minecraft server commands?

**Comment by herobrinein** [comment]
Perhaps it is possible to obtain all registered Minecraft server instructions and use the slack API to add instructions to the bot

**Comment by howyi** [comment]
Thanks for the suggestion. 👍🏿 
This is a console channel feature that is currently under development. We will release it soon.
![](https://raw.githubusercontent.com/howyi/MCSlackIntegration/55298a556ef72e696717488ac6a62f3af0353920/docs/images/console_channel.png)
